# Generated by Django 4.2.3 on 2023-07-13 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('level', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)])),
                ('debt_to_the_supplier', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='trade_network.node')),
            ],
            options={
                'verbose_name': 'trading network member',
                'verbose_name_plural': 'trading network members',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_network.node')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=50, null=True)),
                ('house_number', models.CharField(blank=True, max_length=10, null=True)),
                ('memder_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trade_network.node')),
            ],
            options={
                'verbose_name': 'trading network member contact',
                'verbose_name_plural': 'trading network members contacts',
            },
        ),
    ]
